/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package e03

import java.io.*
import kotlin.concurrent.*

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main(args: Array<String>) {
    println("A")
    if(args.size > 0) {
        readFile(args[0], "utf-8") {
            println(it)
        }
    }
    println("B")
}

fun readFile(file: String, charset: String, block: (String) -> Unit ) {
    thread() {
        try {
            val lines: List<String> = File(file).readLines(charset(charset))
            lines.forEach { block(it) }
        }
        catch(e: IOException) {
            e.printStackTrace()
        }
    }
}