/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package e05

import com.google.gson.Gson
import com.google.gson.stream.JsonReader
import java.io.*
import kotlin.math.pow

data class Person(
    var height: Int,
    var mass: Int,
)

fun main() {
    val g = Gson()
    val f = File("luke.json")
    val jr = JsonReader(FileReader(f))
    val luke: Person = g.fromJson(jr, Person::class.java)
    
    val m = luke.mass
    val h = luke.height.toDouble() / 100

    println(m)
    println(h)

    val bmi = m / h.pow(2)
    println("%.1f".format(bmi))
}
