/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package e01

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }

    /**
    * Searches the array for searchValue. Returns the first index where searchValue
    * is found. If not found, returns null.
    *
    * @param args array to be searched
    * @param searchValue value to be searched for
    * @return either index or null depending if searchValue was found
    */
    fun search(args: Array<Int>, searchValue: Int) : Int? {
        if (args.isEmpty()) throw IllegalArgumentException("non-empty integer array should be given as the argument")

        args.forEach { if (it == searchValue) return it }
        return null  
    }
}

fun main() {
    println(App().greeting)
    App().search(emptyArray<Int>(), 3)
}
