/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package e02

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println("saippuakauppias".isPalindrome()) // true
    println("abc".isPalindrome()) // false
    println("SaippuakauPPias".isPalindrome(ignoreCase = true)) // true
    println("Saippua kauPPias".isPalindrome(ignoreCase = true, ignoreWhiteSpaces = true)) // true
}

fun String.isPalindrome(ignoreCase: Boolean = false, ignoreWhiteSpaces: Boolean = false): Boolean {
    var string = this

    if (ignoreCase) string = string.toLowerCase()
    if (ignoreWhiteSpaces) string = string.trim().filter { !it.isWhitespace() }

    val reversed = string.reversed()

    for (i in 0 until string.length) {
        if (string[i] != reversed[i]) return false
    }

    return true
}